version: "3"

volumes:
  database:
    driver: local

services:
  db:
    image: postgres:13
    container_name: $NODE_ENV
    restart: always
    ports:
      - '$POSTGRES_PORT:5432'
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
