version: "3"

volumes:
  database:
    driver: local

services:
  db:
    image: postgres:13
    container_name: tests
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
